-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (RBAC)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  role text check (role in ('admin', 'guest')) not null,
  full_name text,
  created_at timestamptz default now()
);

-- 2. Scenarios
create table scenarios (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  owner_id uuid references auth.users not null,
  is_shared boolean default false,
  external_sales_retention_pct numeric default 100,
  labor_cost_reduction_target_pct numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Assets
create table assets (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  category text,
  book_value numeric default 0,
  ask_price numeric default 0,
  lease_monthly_cost numeric default 0,
  created_at timestamptz default now()
);

-- 4. Scenario Asset Decisions
create table scenario_asset_decisions (
  scenario_id uuid references scenarios on delete cascade,
  asset_id uuid references assets on delete cascade,
  decision text check (decision in ('buy', 'lease', 'return', 'dispose')),
  primary key (scenario_id, asset_id)
);

-- 5. Audit Logs
create table audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  scenario_id uuid references scenarios,
  target_asset_id uuid references assets,
  action_type text not null,
  details jsonb, -- Stores old_value, new_value
  created_at timestamptz default now()
);

-- 6. Products (Phase 2 Prep)
create table products (
  id uuid default gen_random_uuid() primary key,
  name text,
  cost_material numeric default 0,
  cost_labor_minutes numeric default 0,
  cost_labor_minutes numeric default 0,
  is_composite boolean default false,
  safety_stock numeric default 0,
  lot_size numeric default 100
);

-- Enable RLS
alter table profiles enable row level security;
alter table scenarios enable row level security;
alter table assets enable row level security;
alter table scenario_asset_decisions enable row level security;
alter table audit_logs enable row level security;
alter table products enable row level security;

-- RLS Policies

-- Profiles
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Scenarios
create policy "Admin full access scenarios" on scenarios
  for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Guest view shared scenarios" on scenarios
  for select using (
    exists (select 1 from profiles where id = auth.uid() and role = 'guest') and is_shared = true
  );

-- Assets
create policy "Assets viewable by authenticated" on assets for select to authenticated using (true);
create policy "Assets editable by admin" on assets for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Scenario Asset Decisions
create policy "Decisions full access admin" on scenario_asset_decisions
  for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Decisions view shared guest" on scenario_asset_decisions
  for select using (
     exists (select 1 from scenarios s where s.id = scenario_asset_decisions.scenario_id and s.is_shared = true)
     and exists (select 1 from profiles where id = auth.uid() and role = 'guest')
  );

-- Audit Logs
create policy "Enable insert for authenticated" on audit_logs for insert to authenticated with check (true);
create policy "Enable read for admin" on audit_logs for select using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );
